# The Travis setup:
# - run lint for every PHP version

language: php

php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - hhvm

sudo: false

script:
  - find . -name '*.php' -print0 | xargs -0 -r -n1 php -l
  - ./lint-theme.sh --all
